<?php

namespace Swot\NetworkBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ConversationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConversationRepository extends EntityRepository
{
    public function findConversationBetween(User $user1, User $user2) {
        $query = $this->getEntityManager()->createQuery("
            SELECT c FROM SwotNetworkBundle:Conversation c
            JOIN c.messages m
            JOIN m.from userFrom
            JOIN m.to userTo
            WHERE (
                userFrom = :user1
                AND userTo = :user2
            ) OR (
                userFrom = :user2
                AND userTo = :user1
            )
        ")
        ->setParameter("user1", $user1)
        ->setParameter("user2", $user2)
        ;

        /** @var Conversation $conversation */
        $conversation = $query->getOneOrNullResult();

        return $conversation;
    }
}
