<?php

namespace Swot\NetworkBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RentalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentalRepository extends EntityRepository
{
    /**
     * Finds all active rentals for a thing.
     * A rental is active, if it's granted until date is in the future.
     *
     * @param Thing $thing
     * @return array
     */
    public function findActiveRentals(Thing $thing) {
        $query = $this->getEntityManager()->createQuery("
            SELECT r FROM SwotNetworkBundle:Rental r
            WHERE r.thing = :thing
            AND r.accessGrantedUntil >= :now
        ")
            ->setParameter("thing", $thing)
            ->setParameter("now", new \DateTime())
        ;

        return $query->getResult();
    }
}
