<?php

namespace Swot\NetworkBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ThingStatusUpdateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThingStatusUpdateRepository extends EntityRepository
{
    /**
     * Retrieves newsfeed for given user
     * @param $user
     */
    public function findNewsfeed($user) {

        $query = $this->getEntityManager()->createQuery('
            SELECT c
            FROM SwotNetworkBundle:ThingStatusUpdate c
        ');

        /** @var Newsfeed $newsfeed */
        $newsfeed = $query->getResult();
        return $newsfeed;
    }
}
