<?php

namespace Swot\NetworkBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ThingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ThingRepository extends EntityRepository
{

    public function registerThingToUser(Thing $thing, User $user) {

    }

}
