<?php

namespace Swot\NetworkBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /**
     * Returns all Users who are activated and friends of the passed user.
     * The passed user will be excluded from the list.
     * @param User $user
     * @return array
     */
    public function findFriendsOf(User $user) {
        $query = $this->getEntityManager()->createQuery(
            'SELECT u
             FROM SwotNetworkBundle:Friendship f
             JOIN SwotNetworkBundle:User u
             WHERE (
                f.userWho = :user
                OR f.userWho = :user
             )
             AND u != :user
             AND u.activated = TRUE
             '
        )
            ->setParameter("user", $user)
        ;

        $result = $query->getResult();

        return $result;
    }
}
