my_friends:
    path:     /
    defaults: { _controller: SwotNetworkBundle:Friend:myFriends }

friend_show:
    path:     /{id}
    defaults: { _controller: SwotNetworkBundle:Friend:show }

friend_remove_friendship:
    path:     /{id}/remove
    defaults: { _controller: SwotNetworkBundle:Friend:removeFriendship }
    methods:  [POST, DELETE]

friend_invite:
    path:     /{id}/invite
    defaults: { _controller: SwotNetworkBundle:Friend:sendInvite }
    methods:  [POST, DELETE]