conversations:
    path:     /
    defaults: { _controller: SwotNetworkBundle:Message:conversations }

conversations_since:
    path:     /since/{since}
    defaults: { _controller: SwotNetworkBundle:Message:conversationsSince, since: "0" }

new_message:
    path:     /write
    defaults: { _controller: SwotNetworkBundle:Message:newMessage }

new_conversation:
    path:     /{id}/new
    defaults: { _controller: SwotNetworkBundle:Message:newConversation }

delete_message:
    path:     /{id}/delete
    defaults: { _controller: SwotNetworkBundle:Message:deleteMessage }
    methods:  [POST, DELETE]

conversation:
    path:     /{id}
    defaults: { _controller: SwotNetworkBundle:Message:conversation }

messages_in_conversation_since:
    path:     /{id}/messages/since/{since}
    defaults: { _controller: SwotNetworkBundle:Message:messagesInConversationSince, since: "0" }