conversations:
    path:     /
    defaults: { _controller: SwotNetworkBundle:Message:conversations }

conversation:
    path:     /{id}
    defaults: { _controller: SwotNetworkBundle:Message:conversation }

new_message:
    path:     /write
    defaults: { _controller: SwotNetworkBundle:Message:write }