rental_list:
    path:     /
    defaults: { _controller: SwotNetworkBundle:Rental:list }

rental_quit:
    path:     /{rentalid}
    defaults: { _controller: SwotNetworkBundle:Rental:quit }
    methods:  [DELETE]