register_thing:
    path:   /register
    defaults: { _controller: "SwotNetworkBundle:Thing:register" }

thing_show:
    path:   /{id}
    defaults: { _controller: "SwotNetworkBundle:Thing:show" }

thing_settings:
    path:     /{id}/settings
    defaults: { _controller: "SwotNetworkBundle:Thing:settings" }

thing_delete:
    path:     /{id}/delete
    defaults: { _controller: "SwotNetworkBundle:Thing:delete" }
    methods:  [POST, DELETE]

thing_lend:
    path:     /{id}/lend
    defaults: { _controller: "SwotNetworkBundle:Thing:lend" }

thing_activate_function:
    path:     /{id}/activate/{functionId}
    defaults: { _controller: "SwotNetworkBundle:Thing:activateFunction" }
    methods:  [POST]

thing_update_messages_since:
    path:     /{id}/updates/since/{since}.{_format}
    defaults: { _controller: "SwotNetworkBundle:Thing:showUpdatesSince", _format: "html", since: "0" }
    requirements: { _format: "html|json" }

thing_newsfeed_content:
    path:     /{id}/newsfeed