register_thing:
    path:   /register
    defaults: { _controller: "SwotNetworkBundle:Thing:register" }

thing_show:
    path:   /{id}
    defaults: { _controller: "SwotNetworkBundle:Thing:show" }

thing_delete:
    path:     /{id}/delete
    defaults: { _controller: "SwotNetworkBundle:Thing:delete" }
    methods:  [POST, DELETE]