swot_form_mapper:
    resource: "@SwotFormMapperBundle/Resources/config/routing.yml"
    prefix:   /

swot_network:
    resource: "@SwotNetworkBundle/Resources/config/routing.yml"
    prefix:   /

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"