fos_rest:
    param_fetcher_listener: true
    routing_loader:
        default_format: json
    exception:
        codes:
            'Symfony\Component\Security\Core\Exception\AccessDeniedException': 401
        messages:
            'Symfony\Component\Security\Core\Exception\AccessDeniedException': true