liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        profile_image_thumb:
            quality: 75
            filters:
                thumbnail: { size: [120, 90], mode: outbound }