liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        profile_image_thumb:
            quality: 75
            filters:
                strip: ~
                thumbnail: { size: [120, 90], mode: outbound } # outbound: image will be cropped

        profile_image:
            quality: 75
            filters:
                strip: ~
                thumbnail: { size: [800, 800], mode: inset } # inset: no cropping