liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        profile_image_thumb_tiny:
            quality: 75
            filters:
                strip: ~
                thumbnail: { size: [62, 54], mode: outbound } # outbound: image will be cropped

        profile_image_thumb_small:
            quality: 75
            filters:
                strip: ~
                thumbnail: { size: [96, 84], mode: outbound } # outbound: image will be cropped

        profile_image_thumb_normal:
            quality: 75
            filters:
                strip: ~
                thumbnail: { size: [146, 128], mode: outbound } # outbound: image will be cropped

        profile_image:
            quality: 75
            filters:
                strip: ~
                thumbnail: { size: [800, 800], mode: inset } # inset: no cropping