logout:
    path:   /logout

login:
    path:     /login
    defaults: { _controller: SwotNetworkBundle:Security:login }

login_check:
    path:     /login_check
    defaults: { _controller: SwotNetworkBundle:Security:loginCheck }

newsfeed:
    path:     /
    defaults: { _controller: SwotNetworkBundle:Frontend:newsfeed }

my_friends:
    path:     /friends
    defaults: { _controller: SwotNetworkBundle:Frontend:myFriends }

my_things:
    path:     /things
    defaults: { _controller: SwotNetworkBundle:Frontend:myThings }

delete_thing:
    path:     /things/delete/{id}
    defaults: { _controller: SwotNetworkBundle:Frontend:deleteThing }

#register_user:
#    path:     /register
#    defaults: { _controller: SwotNetworkBundle:Security:register }
