logout:
    path:   /logout

login:
    path:     /login
    defaults: { _controller: SwotNetworkBundle:Security:login }

login_check:
    path:     /login_check
    defaults: { _controller: SwotNetworkBundle:Security:loginCheck }

newsfeed:
    path:     /
    defaults: { _controller: SwotNetworkBundle:Frontend:newsfeed }

newsfeed_since:
    path:     /newsfeed/since/{since}
    defaults: { _controller: SwotNetworkBundle:Frontend:newsfeedSince, since: "0" }

my_things:
    path:     /things
    defaults: { _controller: SwotNetworkBundle:Frontend:myThings }

swot_network_thing:
    resource: "@SwotNetworkBundle/Resources/config/routing/thing.yml"
    prefix:   /things

swot_network_friend:
    resource: "@SwotNetworkBundle/Resources/config/routing/friend.yml"
    prefix:   /friends

swot_network_user:
    resource: "@SwotNetworkBundle/Resources/config/routing/user.yml"
    prefix:   /

swot_network_message:
    resource: "@SwotNetworkBundle/Resources/config/routing/message.yml"
    prefix:   /conversation

swot_network_rental:
    resource: "@SwotNetworkBundle/Resources/config/routing/rental.yml"
    prefix:   /things/{thingid}/rentals

swot_network_thing_rest:
    type: rest
    resource: Swot\NetworkBundle\Controller\ThingRestController

generate_test_data:
    path:     /test
    defaults: { _controller: SwotNetworkBundle:Test:generateTestData }

#register_user:
#    path:     /register
#    defaults: { _controller: SwotNetworkBundle:Security:register }
