logout:
    path:   /logout

login:
    path:     /login
    defaults: { _controller: SwotNetworkBundle:Security:login }

login_check:
    path:     /login_check
    defaults: { _controller: SwotNetworkBundle:Security:loginCheck }

newsfeed:
    path:     /
    defaults: { _controller: SwotNetworkBundle:Frontend:newsfeed }

my_friends:
    path:     /friends
    defaults: { _controller: SwotNetworkBundle:Frontend:myFriends }

#register_user:
#    path:     /register
#    defaults: { _controller: SwotNetworkBundle:Security:register }
