services:
#    swot_network.example:
#        class: Swot\NetworkBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    security.thing_voter:
        class:      Swot\NetworkBundle\Security\ThingVoter
        public:     false
        tags:
           - { name: security.voter }
