parameters:
    swot.directory.upload.profile_images:   'uploads/profileimages/'

services:
    # repositories
    swot.user_repository:
        class: Doctrine\ORM\EntityRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - Swot\NetworkBundle\Entity\User

    swot.image_uploader:
        class:      Swot\NetworkBundle\File\ImageUploader
        arguments: [%kernel.root_dir%, %swot.directory.upload.profile_images%]

    # Security Voters
    security.thing_voter:
        class:      Swot\NetworkBundle\Security\ThingVoter
        public:     false
        tags:
           - { name: security.voter }

    security.user_voter:
        class:      Swot\NetworkBundle\Security\UserVoter
        public:     false
        tags:
           - { name: security.voter }

    security.message_voter:
        class:      Swot\NetworkBundle\Security\MessageVoter
        public:     false
        tags:
           - { name: security.voter }

    # Register form types
    swot.form.type.user_settings:
        class:      Swot\NetworkBundle\Form\UserSettingsType
        tags:
           - { name: form.type, alias: user_settings }

    swot.form.type.new_message:
        class:      Swot\NetworkBundle\Form\NewMessageType
        arguments: [@swot.user_repository, @security.token_storage]
        tags:
           - { name: form.type, alias: new_message }

