services:
#    swot_network.example:
#        class: Swot\NetworkBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    security.thing_voter:
        class:      Swot\NetworkBundle\Security\ThingVoter
        public:     false
        tags:
           - { name: security.voter }

    security.user_voter:
        class:      Swot\NetworkBundle\Security\UserVoter
        public:     false
        tags:
           - { name: security.voter }

    # Register form types
    swot.form.type.user_settings:
        class:      Swot\NetworkBundle\Form\UserSettingsType
        tags:
           - { name: form.type, alias: user_settings }